services:
  snapcast-client:
    image: nickll/snapclient
    command: ["-h", "192.168.0.85", "--hostID", "dc:a6:32:c6:62:6f"]
    container_name: snapcast-client
    restart: unless-stopped
    stdin_open: true
    tty: true
    devices:
      - /dev/snd
