name: Get latest Snapcast release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          API_RESPONSE=$(curl -sL --url https://api.github.com/repos/badaix/snapcast/releases/latest -- header 'authorization: Bearer ${{ secrets.REPO_SCOPED_TOKEN }}')
          echo $API_RESPONSE
          echo $API_RESPONSE | jq -r ".tag_name" | tee .version
      - name: Failsafe if .version contains "null"
        run: |
          if grep -q "null" .version; then
            exit 1
          fi
      - name: Check for modified files
        id: git-check
        run: echo modified=$([ -z "`git status .version --porcelain`" ] && echo "false" || echo "true") | tee -a $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'github-action@github.com'
          git add .version
          git commit -m "New Snapcast release version"
          git push
